import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Navbar from '@/component/Navbar'
import { useState } from 'react'
import { CloseButton, Button} from '@chakra-ui/react'
import Circle from '@/component/effect/Circle'
import { ArrowForwardIcon } from '@chakra-ui/icons'

export default function Home() {
  const [indicationtopPop,setIndicationtopPop] = useState(true)
  const [indicationbottomPop,setIndicationbottomPop] = useState(true)
  const ArratEffectCircle = [
    {x:10,y:10,blur:10},
  ]
  return (
    <>
      <Head>
        <title>Homepage - Coolbask</title>
        <meta name="description" content="Generated by create next app" />
        <meta charset="UTF-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="icon" href="/Logo.png" />
      </Head>

      <header>
        {indicationtopPop? 
        <div className={styles.information}>
          <h5>Você possue um time favorito?</h5>
          <p> Fique por dentro de tudo em nosso site.</p>
          <a>Coolbask</a>
          <i class="arrow alternate circle right icon"></i>
          <CloseButton 
            onClick={()=>{
              setIndicationtopPop(false)
            }}/>
        </div>
        : 
        <></> }
        <Navbar />
        </header>

        <main className={styles.Main}>
            <Circle h={80} color='linear-gradient(0deg, rgba(255,133,0,1) 0%, rgba(255,133,0,.1) 92%);'/>
            <section className={styles.MainSection}>
              <h1>connect to one of the biggest sports networks, Here you can find everything</h1>
              <br/>
              <Button rightIcon={<ArrowForwardIcon />} colorScheme='orange' width='200px' size='lg' variant='solid'>Call us</Button>
            </section>
        </main>

        <footer>

        {indicationbottomPop? 
        <div className={styles.PopModalBottom}>
          <div className={styles.PopModalBottomCont}>
          <h5>Utilizaremos cookies para melhor experiencia em sua navegação! ⚡</h5>
            <CloseButton 
            onClick={()=>{
            setIndicationbottomPop(false)
          }}
          />
          </div>
          
        </div>
        :
        <h5></h5>
        }
        </footer>
    </>
  )
}
